// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC7YLsQfiagwaijWpGzC6KCKJdc6_n0Uw',
    appId: '1:830214496878:web:c6ea33c428d2f4e3a9fc7f',
    messagingSenderId: '830214496878',
    projectId: 'quran-app-a1c2f',
    authDomain: 'quran-app-a1c2f.firebaseapp.com',
    storageBucket: 'quran-app-a1c2f.firebasestorage.app',
    measurementId: 'G-EHVMC816DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEOjWYTOFsB5WJgglWW_ToxsOcxaf_bMI',
    appId: '1:830214496878:android:a7d8b33fca853f24a9fc7f',
    messagingSenderId: '830214496878',
    projectId: 'quran-app-a1c2f',
    storageBucket: 'quran-app-a1c2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKH7RlmYSiaZd0W9RwfSSTbMf-o_ULGZA',
    appId: '1:830214496878:ios:13af6c1a82b2cb65a9fc7f',
    messagingSenderId: '830214496878',
    projectId: 'quran-app-a1c2f',
    storageBucket: 'quran-app-a1c2f.firebasestorage.app',
    iosBundleId: 'com.abushofa.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKH7RlmYSiaZd0W9RwfSSTbMf-o_ULGZA',
    appId: '1:830214496878:ios:8520ce7574d40432a9fc7f',
    messagingSenderId: '830214496878',
    projectId: 'quran-app-a1c2f',
    storageBucket: 'quran-app-a1c2f.firebasestorage.app',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC7YLsQfiagwaijWpGzC6KCKJdc6_n0Uw',
    appId: '1:830214496878:web:ec178b3a90ad54aba9fc7f',
    messagingSenderId: '830214496878',
    projectId: 'quran-app-a1c2f',
    authDomain: 'quran-app-a1c2f.firebaseapp.com',
    storageBucket: 'quran-app-a1c2f.firebasestorage.app',
    measurementId: 'G-T23TFFZ5QB',
  );
}
